version: '3.2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - dockerwp
    restart: always
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dockerwp
    restart: always
  app:
    container_name: api-v2-0.0.1
    image: api-v2-0.0.1
    build: ./
    expose:
      - 80
      - 5432
    environment:
      VIRTUAL_HOST: 'api.ccpidsuscal.com'
      VIRTUAL_PORT: 80  
      LETSENCRYPT_HOST: 'api.ccpidsuscal.com'
      LETSENCRYPT_EMAIL: 'xavi@kpyvara.com'
    networks:
      - dockerwp
    restart: always
  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./front:/usr/share/nginx/html:ro
    environment:
      VIRTUAL_HOST: 'ccpidsuscal.com' 
      LETSENCRYPT_HOST: 'ccpidsuscal.com'
      LETSENCRYPT_EMAIL: 'xavi@kpyvara.com'
    networks:
      - dockerwp
networks:
  dockerwp:
volumes:
  certs:
  html:
  vhostd:
 

